/** @type {import('next').NextConfig} */
const nextConfig = {
  //
  // ─── Images ────────────────────────────────────────────────────────────────
  // Allow next/image to optimise images served from Supabase storage.
  // Add any additional hostnames used by thumbnails / avatars here.
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**.supabase.co',
        pathname: '/storage/v1/object/public/**',
      },
      {
        // Google profile pictures used by OAuth avatars
        protocol: 'https',
        hostname: 'lh3.googleusercontent.com',
      },
      {
        // Google icon SVG used on Sign-in buttons (Navbar, SignInGateModal)
        protocol: 'https',
        hostname: 'www.gstatic.com',
      },
    ],
  },

  // ─── Performance ───────────────────────────────────────────────────────────
  // Compress HTML/JS responses with gzip (enabled by default on Vercel, but
  // explicit here for self-hosted fallback)
  compress: true,

  // ─── TypeScript ───────────────────────────────────────────────────────────
  // Types are clean after upgrading @supabase/ssr → 0.10.3 and
  // @supabase/supabase-js → 2.106.0 to align with the __InternalSupabase
  // PostgrestVersion format generated by the Supabase CLI.
  typescript: {
    ignoreBuildErrors: false,
  },
  // ─── ESLint ───────────────────────────────────────────────────────────────
  // src/ removed — ESLint checks re-enabled.
  eslint: {
    ignoreDuringBuilds: false,
  },
};

export default nextConfig;
